name: talabak_express
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.0
  image_picker: ^1.1.2
  http: ^1.4.0
  flutter_charts: ^0.5.2
  community_charts_flutter: ^1.0.4
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  onesignal_flutter: ^5.3.3
  flutter_launcher_icons: ^0.14.3
  whatsapp_unilink: ^2.1.0
  location: ^8.0.0
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^19.3.1
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"

flutter:
  uses-material-design: true

  assets:
    - assets/talabak.png
    - assets/box.png
    - assets/playstore.png
