// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWtkmbQibf3gfNfudx5seWejnOV1sNvw',
    appId: '1:124219820643:android:c21351d4e04ff71e1b0656',
    messagingSenderId: '124219820643',
    projectId: 'talabak-express',
    storageBucket: 'talabak-express.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyg8VGqYKlejGOT4Vwhd-NXVsgRO0ajM',
    appId: '1:124219820643:ios:020dcc9a0f2cfc2d1b0656',
    messagingSenderId: '124219820643',
    projectId: 'talabak-express',
    storageBucket: 'talabak-express.firebasestorage.app',
    iosBundleId: 'com.talabak.express',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHF5DDGtoTFuU0CgorEFOizfNaOX3ojko',
    appId: '1:124219820643:web:e8fa7df66903adac1b0656',
    messagingSenderId: '124219820643',
    projectId: 'talabak-express',
    authDomain: 'talabak-express.firebaseapp.com',
    storageBucket: 'talabak-express.firebasestorage.app',
    measurementId: 'G-4M6B096ZQM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyg8VGqYKlejGOT4Vwhd-NXVsgRO0ajM',
    appId: '1:124219820643:ios:93d83518e1ce94f91b0656',
    messagingSenderId: '124219820643',
    projectId: 'talabak-express',
    storageBucket: 'talabak-express.firebasestorage.app',
    iosBundleId: 'com.example.talabakExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHF5DDGtoTFuU0CgorEFOizfNaOX3ojko',
    appId: '1:124219820643:web:70be2129cbbc84aa1b0656',
    messagingSenderId: '124219820643',
    projectId: 'talabak-express',
    authDomain: 'talabak-express.firebaseapp.com',
    storageBucket: 'talabak-express.firebasestorage.app',
    measurementId: 'G-FPLTCW94Q8',
  );

}